# kind: pipeline
# type: ssh
# name: scoutrobot
#
# server:
#   host: zoomyboy.de
#   user: stammsilva
#   ssh_key:
#     from_secret: private_key
#
# clone:
#   disable: true
#
# steps:
# - name: master
#   commands:
#   - /usr/local/bin/deploy_scoutrobot_master
#   when:
#     branch:
#     - master
#     event:
#     - push
#
kind: pipeline
type: docker
name: default

workspace:
    path: /drone/nami

steps:
    - name: submodules
      image: alpine/git
      environment:
          SSH_KEY:
              from_secret: private_key
          KNOWN_HOSTS:
              from_secret: known_hosts
      commands:
          - mkdir $HOME/.ssh
          - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
          - echo "$KNOWN_HOSTS" > $HOME/.ssh/known_hosts
          - cat $HOME/.ssh/known_hosts
          - chmod 600 $HOME/.ssh/id_rsa
          - git submodule update --init --recursive

    - name: composer
      image: composer:2.2.7
      commands:
          - composer install --ignore-platform-reqs --no-dev

    - name: node
      image: node:17.9.0-slim
      commands:
          - npm install && npm run prod && rm -R node_modules

    - name: compress
      image: php:7.3
      commands:
          - apt-get update -yqq
          - apt-get install -yqq zip tar
          - cd .. && tar -cvzf nami.tar.gz ./nami && mv nami.tar.gz nami/ && cd nami
      when:
          event: tag

    - name: gitea_release
      image: plugins/gitea-release
      settings:
          api_key:
              from_secret: gitea_api_key
          base_url: https://git.zoomyboy.de
          files: ./nami.tar.gz
      when:
          event: tag

trigger:
    event:
        - push
        - tag
