# kind: pipeline
# type: ssh
# name: scoutrobot
#
# server:
#   host: zoomyboy.de
#   user: stammsilva
#   ssh_key:
#     from_secret: private_key
#
# clone:
#   disable: true
#
# steps:
# - name: master
#   commands:
#   - /usr/local/bin/deploy_scoutrobot_master
#   when:
#     branch:
#     - master
#     event:
#     - push
#
kind: pipeline
type: docker
name: default

steps:
    - name: submodules
      image: alpine/git
      commands:
          - git submodule update --init --recursive
    - name: test
      image: docker:latest
      commands:
          - docker build -t scoutrobot .
      when:
          branch:
              - master
          event:
              - push
