kind: pipeline
type: docker
name: default

workspace:
    path: /drone/nami

steps:
    - name: submodules
      image: alpine/git
      environment:
          SSH_KEY:
              from_secret: private_key
          KNOWN_HOSTS:
              from_secret: known_hosts
      commands:
          - mkdir $HOME/.ssh
          - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
          - echo "$KNOWN_HOSTS" > $HOME/.ssh/known_hosts
          - chmod 600 $HOME/.ssh/id_rsa
          - git submodule update --init --recursive

    - name: composer_dev
      image: composer:2.2.7
      commands:
          - composer install --ignore-platform-reqs --dev

    - name: mysql_healthcheck
      image: mariadb/server:10.3
      commands:
          - while ! mysqladmin ping -h db -u db -pdb --silent; do sleep 1; done

    - name: node
      image: node:17.9.0-slim
      commands:
          - npm ci && npm run prod && npm run img && rm -R node_modules

    - name: composer_no_dev
      image: composer:2.2.7
      commands:
          - composer install --ignore-platform-reqs --no-dev

    - name: compress
      image: php:7.3
      commands:
          - apt-get update -yqq
          - apt-get install -yqq zip tar
          - cd .. && tar -cvzf nami.tar.gz ./nami && mv nami.tar.gz nami/ && cd nami
      when:
          event: tag

    - name: gitea_release
      image: plugins/gitea-release
      settings:
          api_key:
              from_secret: gitea_api_key
          base_url: https://git.zoomyboy.de
          files: ./nami.tar.gz
      when:
          event: tag

    - name: deploy silva
      image: drillster/drone-rsync
      settings:
          hosts: ['zoomyboy.de']
          user: stammsilva
          source: ./
          target: ~/nami
          exclude: ['.git']
          key:
              from_secret: private_key
          script:
              - cd ~/nami
              - /usr/bin/php8.1 artisan migrate --force
      when:
          branch: master
          event: push

    - name: deploy lennep
      image: drillster/drone-rsync
      settings:
          hosts: ['zoomyboy.de']
          user: dpsg-lennep
          source: ./
          target: ~/nami
          exclude: ['.git']
          key:
              from_secret: private_key
          script:
              - cd ~/nami
              - /usr/bin/php8.1 artisan migrate --force
      when:
          branch: master
          event: push

    - name: deploy dpsgkoeln
      image: drillster/drone-rsync
      settings:
          hosts: ['dpsg-koeln.de']
          user: dpsg-koeln
          source: ./
          target: ~/adrema
          exclude: ['.git']
          key:
              from_secret: private_key
          script:
              - cd ~/adrema
              - /usr/bin/php8.1 artisan migrate --force
              - sudo systemctl restart adrema-horizon
      when:
          branch: master
          event: push

services:
    - name: db
      image: mariadb/server:10.3
      environment:
          MARIADB_DATABASE: db
          MARIADB_USER: db
          MARIADB_PASSWORD: db
          MARIADB_ALLOW_EMPTY_PASSWORD: yes
    - name: redis
      image: redis

trigger:
    event:
        - push
        - tag
