# kind: pipeline
# type: ssh
# name: scoutrobot
#
# server:
#   host: zoomyboy.de
#   user: stammsilva
#   ssh_key:
#     from_secret: private_key
#
# clone:
#   disable: true
#
# steps:
# - name: master
#   commands:
#   - /usr/local/bin/deploy_scoutrobot_master
#   when:
#     branch:
#     - master
#     event:
#     - push
#
kind: pipeline
type: docker
name: default

steps:
    - name: submodules
      image: alpine/git
      environment:
          SSH_KEY:
              from_secret: new_private_key
          KNOWN_HOSTS:
              from_secret: known_hosts
      commands:
          - mkdir $HOME/.ssh
          - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
          - echo "$KNOWN_HOSTS" > $HOME/.ssh/known_hosts
          - cat $HOME/.ssh/known_hosts
          - chmod 600 $HOME/.ssh/id_rsa
          - git submodule update --init --recursive
      when:
          branch:
              - dev
          event:
              - push

    - name: composer
      image: composer:2.2.7
      commands:
          - composer install --ignore-platform-reqs --no-dev
      when:
          branch:
              - dev
          event:
              - push

    - name: node
      image: node:17.9.0-slim
      commands:
          - npm install && npm run prod && rm -R node_modules
      when:
          branch:
              - dev
          event:
              - push

