version: '1'
services:
  webservice:
    image: nginx:1.21.6-alpine
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    build:
      context: .
      dockerfile: ./.docker/php.Dockerfile
    container_name: php
    depends_on:
      - db
      - dbtest
    command: php-fpm -F -R
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
      image: mariadb:10.6.5
      container_name: db
      environment:
        MARIADB_ROOT_PASSWORD: local
        MYSQL_PASSWORD: local
        MYSQL_DATABASE: db
        MYSQL_USER: db
      volumes:
          - /opt/mysql-docker/scoutrobot-db:/var/lib/mysql
  dbtest:
      image: mariadb:10.6.5
      container_name: dbtest
      environment:
        MARIADB_ROOT_PASSWORD: local
        MYSQL_PASSWORD: local
        MYSQL_DATABASE: db
        MYSQL_USER: db
      volumes:
          - /opt/mysql-docker/scoutrobot-dbtest:/var/lib/mysql
