/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FCheckboxesLabel: typeof import('@/components/form/CheckboxesLabel.vue')['default']
    FEditor: typeof import('@/components/form/Editor.vue')['default']
    FHint: typeof import('@/components/form/Hint.vue')['default']
    FLabel: typeof import('@/components/form/Label.vue')['default']
    FMemberFilter: typeof import('@/components/form/MemberFilter.vue')['default']
    FMultipleselect: typeof import('@/components/form/Multipleselect.vue')['default']
    FSaveButton: typeof import('@/components/form/SaveButton.vue')['default']
    FSelect: typeof import('@/components/form/Select.vue')['default']
    FSwitch: typeof import('@/components/form/Switch.vue')['default']
    FText: typeof import('@/components/form/Text.vue')['default']
    FTextarea: typeof import('@/components/form/Textarea.vue')['default']
    PageFilter: typeof import('@/components/page/Filter.vue')['default']
    PageFullHeading: typeof import('@/components/page/FullHeading.vue')['default']
    PageFullHeadingBanner: typeof import('@/components/page/FullHeadingBanner.vue')['default']
    PageFullLayout: typeof import('@/components/page/FullLayout.vue')['default']
    PageHeader: typeof import('@/components/page/Header.vue')['default']
    PageLayout: typeof import('@/components/page/Layout.vue')['default']
    PageSearchModal: typeof import('@/components/page/SearchModal.vue')['default']
    PageTitle: typeof import('@/components/page/Title.vue')['default']
    PageToolbarButton: typeof import('@/components/page/ToolbarButton.vue')['default']
    UiActionButton: typeof import('@/components/ui/ActionButton.vue')['default']
    UiAgeGroups: typeof import('@/components/ui/AgeGroups.vue')['default']
    UiBool: typeof import('@/components/ui/Bool.vue')['default']
    UiBooleanDisplay: typeof import('@/components/ui/BooleanDisplay.vue')['default']
    UiBox: typeof import('@/components/ui/Box.vue')['default']
    UiButton: typeof import('@/components/ui/Button.vue')['default']
    UiFilterSidebar: typeof import('@/components/ui/FilterSidebar.vue')['default']
    UiIconButton: typeof import('@/components/ui/IconButton.vue')['default']
    UiLabel: typeof import('@/components/ui/Label.vue')['default']
    UiLoading: typeof import('@/components/ui/Loading.vue')['default']
    UiMenulist: typeof import('@/components/ui/Menulist.vue')['default']
    UiNote: typeof import('@/components/ui/Note.vue')['default']
    UiPagination: typeof import('@/components/ui/Pagination.vue')['default']
    UiPopup: typeof import('@/components/ui/Popup.vue')['default']
    UiRemoteResource: typeof import('@/components/ui/RemoteResource.vue')['default']
    UiRemoteSelector: typeof import('@/components/ui/RemoteSelector.vue')['default']
    UiSearchPagination: typeof import('@/components/ui/SearchPagination.vue')['default']
    UiSearchResult: typeof import('@/components/ui/SearchResult.vue')['default']
    UiSidebar: typeof import('@/components/ui/Sidebar.vue')['default']
    UiSpinner: typeof import('@/components/ui/Spinner.vue')['default']
    UiSprite: typeof import('@/components/ui/Sprite.vue')['default']
    UiTableToggleButton: typeof import('@/components/ui/TableToggleButton.vue')['default']
    UiTabs: typeof import('@/components/ui/Tabs.vue')['default']
    UiTextDisplay: typeof import('@/components/ui/TextDisplay.vue')['default']
    UiTh: typeof import('@/components/ui/Th.vue')['default']
  }
}
